require("plugins")
require("lsp")
require("settings")
require("mappings")
require("coc")
require("gitsigns")
require('wlsample.airline')

vim.cmd('colorscheme bow-wob')
vim.cmd('highlight SignColumn guibg=bow-wob')
